//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vecinos
    {
        public Vecinos()
        {
            this.Ciudads = new HashSet<Ciudad>();
        }
    
        public int idVecino { get; set; }
        public int Pasos { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Ciudad> Ciudads { get; set; }
    }
}
